"""add email to users

Revision ID: 154f6008ea84
Revises: a64880a42469
Create Date: 2026-03-04 17:15:43.314806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154f6008ea84'
down_revision = 'a64880a42469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
